### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by Link2Twenty** [anthfran/polymer-instagram-post#1]
Hello,  I forked your project and added a few best practices.
I would have submitted a pull request but I wasn't sure if you'd like to include any/all of them.

The forked copy is [here](https://github.com/Link2Twenty/polymer-instagram-post/blob/master/instagram-post.html).

I added:
 - Support for a hidden attribute on the host
 - Comments for properties and functions (these appear in the auto-documentation)
 - An object to store the post data rather than having lots of properties
 - Underscores in front of properties/functions that shouldn't be accessed by the user

I also but all the properties/functions in alphabetical order.

I hope you find some of this helpful 🙂

**Comment by anthfran** [comment]
Thanks for these best practices, I'm still learning Polymer. 

I originally had an object to store the post data, but it didn't work and it seems yours doesn't either. It seems to get the object okay from Instagram but receives GET 404's for the image.

**Comment by Link2Twenty** [comment]
It's a very good element, that's why it caught my attention 🙂

Hmm, it was working for me.
Here is a demo running my fork.
https://jsfiddle.net/link2twenty/wpwaqdxv/

**Comment by anthfran** [comment]
Hmm, I guess it only happens when there's a second <instagram-post> on the same page.

https://jsfiddle.net/wpwaqdxv/2/

**Comment by Link2Twenty** [comment]
I'm getting an error from https://cors.io/?https://www.instagram.com/p/BegRINbDK7p/?__a=1 now

Error 503 Over Quota

**Comment by anthfran** [comment]
Ah.. there's an issue currently with cors.io

That isn't necessary on a real webserver, but "polymer serve" doesn't support CORS

**Comment by anthfran** [comment]
I've figured it out. Will be pushing a new version with some of your code implemented as well. Thanks for the help!

**Comment by Link2Twenty** [comment]
No worries
